export interface IUser {
    uid: string
    name: string
    email: string
    roles: string[]
    rut: string
    hasContract: boolean
    latitude: number
    longitude: number
    location_update: string
    isApproved: boolean
    fcmTokens: string[]
    readOnly: boolean
    companyId: string
    companyName: string
    allowDynamicRoutes: boolean
    ticketsCount: number
    level: number
    isAvailable: boolean
    tikerPhoneNumber: string
    tikerEmergencyPhoneNumber: string
    tikerEmail: string
    pictureUrl: string
    countryId: string
    rating: number
    enabledAvailable: boolean
    environmentIds: string[]
    projectIds: string[]
}